---
title: Sleek
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: GitHub User
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: "/"
url: https://janczizikow.github.io/sleek
twitter_username: jan_czizikow
github_username: janczizikow
instagram_username: shanlongjj
social:
  name: Your Name
  links:
  - https://twitter.com/BenBalter
  - https://www.facebook.com/ben.balter
  - https://www.linkedin.com/in/BenBalter
  - https://plus.google.com/+BenBalter
  - https://github.com/benbalter
  - https://keybase.io/benbalter
disqus:
  shortname: janczizikow
markdown: kramdown
highlighter: rouge
theme: jekyll-sleek
exclude:
- README.md
- node_modules
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- vendor
- npm-debug.log
- gulpfile.js
- sleek.png
include:
- _pages
permalink: "/:title/"
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
- jekyll-seo-tag
