---
title: stJL .blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: stJL
email: stujueling@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: "/"
url: https://stjl.github.io/webdevelop
twitter_username: stujueling
github_username: stujueling
instagram_username: stujueling
social:
  name: stujueling
  links:
  - https://twitter.com/stujueling
  - https://www.facebook.com/stujueling
  - https://www.linkedin.com/in/stujueling
  - https://plus.google.com/stujueling
  - https://github.com/stujueling
disqus:
  shortname: 
markdown: kramdown
highlighter: rouge
theme: jekyll-sleek
exclude:
- README.md
- node_modules
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- vendor
- npm-debug.log
- gulpfile.js
- sleek.png
include:
- _pages
permalink: "/:title/"
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
- jekyll-seo-tag
